options = {
  trajectory_builder = {
    trajectory_builder_2d = {
      use_online_correlative_scan_matching = false,
      num_accumulated_range_data = 1,
      max_range = 30.0,
      missing_data_ray_length = 5.0,
      min_z = -0.8,
      voxel_filter_size = 0.025,
      loop_closure_adaptive_voxel_filter = {
        max_length = 0.9,
        max_range = 50.0,
        min_num_points = 100,
      },
      min_range = 0.0,
      motion_filter = {
        max_time_seconds = 5.0,
        max_angle_radians = 0.017453292519943295,
        max_distance_meters = 0.2,
      },
      use_imu_data = true,
      submaps = {
        range_data_inserter = {
          tsdf_range_data_inserter = {
            update_weight_angle_scan_normal_to_ray_kernel_bandwidth = 0.5,
            maximum_weight = 10.0,
            update_weight_distance_cell_to_hit_kernel_bandwidth = 0.5,
            normal_estimation_options = {
              sample_radius = 0.5,
              num_normal_samples = 4,
            },
            update_free_space = false,
            truncation_distance = 0.3,
            update_weight_range_exponent = 0,
            project_sdf_distance_to_scan_normal = true,
          },
          probability_grid_range_data_inserter = {
            miss_probability = 0.49,
            insert_free_space = true,
            hit_probability = 0.55,
          },
          range_data_inserter_type = "PROBABILITY_GRID_INSERTER_2D",
        },
        num_range_data = 90,
        grid_options_2d = {
          resolution = 0.05,
          grid_type = "PROBABILITY_GRID",
        },
      },
      pose_extrapolator = {
        imu_based = {
          pose_queue_duration = 5.0,
          odometry_translation_weight = 1.0,
          imu_acceleration_weight = 1.0,
          odometry_rotation_weight = 1.0,
          pose_translation_weight = 1.0,
          imu_rotation_weight = 1.0,
          solver_options = {
            use_nonmonotonic_steps = false,
            num_threads = 1,
            max_num_iterations = 10,
          },
          pose_rotation_weight = 1.0,
          gravity_constant = 9.806,
        },
        use_imu_based = false,
        constant_velocity = {
          imu_gravity_time_constant = 10.0,
          pose_queue_duration = 0.001,
        },
      },
      imu_gravity_time_constant = 10.0,
      real_time_correlative_scan_matcher = {
        linear_search_window = 0.1,
        angular_search_window = 0.3490658503988659,
        translation_delta_cost_weight = 0.1,
        rotation_delta_cost_weight = 0.1,
      },
      ceres_scan_matcher = {
        occupied_space_weight = 1.0,
        translation_weight = 10.0,
        ceres_solver_options = {
          use_nonmonotonic_steps = false,
          num_threads = 1,
          max_num_iterations = 20,
        },
        rotation_weight = 40.0,
      },
      max_z = 2.0,
      adaptive_voxel_filter = {
        max_length = 0.5,
        max_range = 50.0,
        min_num_points = 200,
      },
    },
    collate_fixed_frame = false,
    trajectory_builder_3d = {
      voxel_filter_size = 0.256,
      min_range = 0.2,
      submaps = {
        high_resolution_max_range = 50.0,
        range_data_inserter = {
          miss_probability = 0.49,
          hit_probability = 0.55,
          num_free_space_voxels = 2,
        },
        num_range_data = 651,
        low_resolution = 0.466,
        high_resolution = 0.127,
      },
      num_accumulated_range_data = 1,
      pose_extrapolator = {
        imu_based = {
          pose_queue_duration = 5.0,
          odometry_translation_weight = 1.0,
          imu_acceleration_weight = 1.0,
          odometry_rotation_weight = 1.0,
          pose_translation_weight = 1.0,
          imu_rotation_weight = 1.0,
          solver_options = {
            use_nonmonotonic_steps = false,
            num_threads = 1,
            max_num_iterations = 10,
          },
          pose_rotation_weight = 1.0,
          gravity_constant = 9.806,
        },
        use_imu_based = false,
        constant_velocity = {
          imu_gravity_time_constant = 10.0,
          pose_queue_duration = 0.001,
        },
      },
      imu_gravity_time_constant = 10.0,
      motion_filter = {
        max_time_seconds = 0.5,
        max_angle_radians = 0.004,
        max_distance_meters = 0.1,
      },
      rotational_histogram_size = 120,
      ceres_scan_matcher = {
        rotation_weight = 51,
        only_optimize_yaw = false,
        translation_weight = 3,
        occupied_space_weight_1 = 6.0,
        ceres_solver_options = {
          use_nonmonotonic_steps = false,
          num_threads = 1,
          max_num_iterations = 12,
        },
        occupied_space_weight_0 = 1.0,
      },
      use_online_correlative_scan_matching = false,
      real_time_correlative_scan_matcher = {
        linear_search_window = 0.15,
        angular_search_window = 0.017453292519943295,
        translation_delta_cost_weight = 0.1,
        rotation_delta_cost_weight = 0.1,
      },
      max_range = 112,
      low_resolution_adaptive_voxel_filter = {
        max_length = 3,
        max_range = 67,
        min_num_points = 278,
      },
      high_resolution_adaptive_voxel_filter = {
        max_length = 3,
        max_range = 42,
        min_num_points = 186,
      },
    },
    collate_landmarks = false,
  },
  tracking_frame = "fcu",
  published_frame = "fcu",
  provide_odom_frame = false,
  map_builder = {
    use_trajectory_builder_3d = true,
    use_trajectory_builder_2d = false,
    pose_graph = {
      optimization_problem = {
        fixed_frame_pose_translation_weight = 10.0,
        odometry_translation_weight = 100000.0,
        ceres_solver_options = {
          use_nonmonotonic_steps = false,
          num_threads = 7,
          max_num_iterations = 200,
        },
        huber_scale = 500.0,
        local_slam_pose_rotation_weight = 100000.0,
        fixed_frame_pose_use_tolerant_loss = false,
        fix_z_in_3d = false,
        acceleration_weight = 100.0,
        rotation_weight = 0.0,
        use_online_imu_extrinsics_in_3d = true,
        fixed_frame_pose_tolerant_loss_param_a = 1,
        fixed_frame_pose_rotation_weight = 100.0,
        log_solver_summary = false,
        fixed_frame_pose_tolerant_loss_param_b = 1,
        local_slam_pose_translation_weight = 100000.0,
        odometry_rotation_weight = 100000.0,
      },
      matcher_rotation_weight = 1600.0,
      optimize_every_n_nodes = 0,
      constraint_builder = {
        loop_closure_translation_weight = 11000.0,
        fast_correlative_scan_matcher_3d = {
          min_rotational_score = 0.77,
          branch_and_bound_depth = 8,
          angular_search_window = 0.2617993877991494,
          linear_xy_search_window = 5.0,
          linear_z_search_window = 1.0,
          full_resolution_depth = 3,
          min_low_resolution_score = 0.55,
        },
        min_score = 0.4,
        loop_closure_rotation_weight = 100000.0,
        ceres_scan_matcher_3d = {
          rotation_weight = 1.0,
          only_optimize_yaw = false,
          translation_weight = 10.0,
          occupied_space_weight_1 = 30.0,
          ceres_solver_options = {
            use_nonmonotonic_steps = false,
            num_threads = 1,
            max_num_iterations = 10,
          },
          occupied_space_weight_0 = 5.0,
        },
        fast_correlative_scan_matcher = {
          linear_search_window = 7.0,
          angular_search_window = 0.5235987755982988,
          branch_and_bound_depth = 7,
        },
        max_constraint_distance = 30.0,
        log_matches = true,
        ceres_scan_matcher = {
          occupied_space_weight = 20.0,
          translation_weight = 10.0,
          ceres_solver_options = {
            use_nonmonotonic_steps = true,
            num_threads = 1,
            max_num_iterations = 10,
          },
          rotation_weight = 1.0,
        },
        global_localization_min_score = 0.66,
        sampling_ratio = 0.02,
      },
      max_num_final_iterations = 200,
      global_constraint_search_after_n_seconds = 10.0,
      global_sampling_ratio = 0.003,
      matcher_translation_weight = 500.0,
      log_residual_histograms = true,
    },
    num_background_threads = 3,
    collate_by_trajectory = false,
  },
  use_nav_sat = false,
  landmarks_sampling_ratio = 1.0,
  imu_sampling_ratio = 1.0,
  use_pose_extrapolator = true,
  odom_frame = "viv/odom",
  num_point_clouds = 1,
  publish_frame_projected_to_2d = false,
  trajectory_publish_period_sec = 0.03,
  rangefinder_sampling_ratio = 1.0,
  num_laser_scans = 0,
  map_frame = "map",
  pose_publish_period_sec = 0.002,
  submap_publish_period_sec = 0.3,
  lookup_transform_timeout_sec = 0.2,
  use_landmarks = false,
  num_multi_echo_laser_scans = 0,
  use_odometry = false,
  num_subdivisions_per_laser_scan = 1,
  fixed_frame_pose_sampling_ratio = 1.0,
  odometry_sampling_ratio = 1.0,
}

return options
